# These are supported funding model platforms

github: # [user1, user2]
custom: ['https://hui-zz.gitee.io/runany/assets/images/%E6%94%AF%E6%8C%81RunAny.jpg', 'https://hui-zz.gitee.io/runany/assets/images/%E6%94%AF%E6%8C%81RunAny.png']
